export const ProductData = [
  {
    _id: "1",
    img: "https://www.ikea.com/om/en/images/products/fejka-artificial-potted-plant-in-outdoor-monstera__0614197_pe686822_s5.jpg?f=s",
    productName: "Monstera",
    category: "plant",
    price: "500",
    slug: "Monstera",
    countInStock: 0,
    rating: 3,
  },
  {
    _id: "2",
    img: "https://m.media-amazon.com/images/I/61MNGrjDTNS._SX466_.jpg",
    productName: "Guuchu Jade",
    category: "Plant",
    price: "200",
    slug: "Guuchu_Jade",
    countInStock: 8,
    rating: 3.5,
  },
  {
    _id: "3",
    img: "https://assets.eflorist.com/assets/products/PHR_/TPL12-1A.jpg",
    productName: "Teleflora's Luxe Leaves",
    category: "Plant",
    price: "100",
    slug: "Teleflora's_Luxe_Leaves",
    countInStock: 10,
    rating: 2.5,
  },
  {
    _id: "4",
    img: "https://target.scene7.com/is/image/Target/GUEST_415f6a69-d464-4620-ac4a-e499ecae2731?wid=488&hei=488&fmt=pjpeg",
    productName: "Costa Farms  Snake Plant",
    category: "Plant",
    price: "1000",
    slug: "Costa_Farms_Snake_Plant",
    countInStock: 2,
    rating: 2.0,
  },
];
